model {
  file: "model.sdf"
}
name: "DINNING_ROOM_FURNITURE_SET_1"
description: "DINNING ROOM (FURNITURE SET 1)\nThis set includes a dining table, a cabinet, and four chairs. Made of Eco-Friendly PlanWood and solid rubber wood."
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "PlanToys"
}
annotations {
  key: "mpn"
  value: "7604"
}
annotations {
  key: "sku"
  value: "07604P00"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Toys"
}
